import logging
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, MessageHandler, CallbackQueryHandler, filters, ContextTypes
from app.config import TELEGRAM_BOT_TOKEN, PAYSTACK_BASIC_PLAN, PAYSTACK_PRO_PLAN
from app.database import supabase
from app.payments import register_user, get_user, create_subscription_link, upgrade_user
from app.ai import get_ai_response
from datetime import datetime, UTC

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

user_histories = {}

TERMS_TEXT = """📋 Terms & Conditions

By using StockOracle you agree to the following:

1. StockOracle provides financial information and analysis for educational purposes only. It is NOT financial advice.

2. All stock signals and analysis are generated by algorithms and AI. Past performance does not guarantee future results.

3. You are solely responsible for your own investment decisions. StockOracle and SireAI accept no liability for any financial losses.

4. Subscriptions are billed monthly. Cancellations take effect at the end of the current billing period.

5. We do not guarantee the accuracy of real-time market data. Always verify prices with your broker before trading.

6. By subscribing, you consent to receiving automated market alerts and signals via Telegram.

Do you accept these terms?"""

def is_paid(user: dict) -> bool:
    if not user:
        return False

    if user.get("tier") not in ["basic", "pro"]:
        return False

    expires_at = user.get("expires_at")
    if not expires_at:
        return False

    try:
        from datetime import timezone
        exp = datetime.fromisoformat(expires_at.replace("Z", "+00:00"))
        if exp.tzinfo is None:
            exp = exp.replace(tzinfo=timezone.utc)
        if exp <= datetime.now(UTC):
            supabase.table("users").update({
                "tier": "free"
            }).eq("telegram_id", user["telegram_id"]).execute()
            return False
        return True
    except:
        return False

def is_pro(user: dict) -> bool:
    if not is_paid(user):
        return False
    return user.get("tier") == "pro"

def has_accepted_terms(user: dict) -> bool:
    if not user:
        return False
    return user.get("terms_accepted", False)

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    telegram_id = update.effective_user.id
    name = update.effective_user.first_name or "there"

    user = get_user(telegram_id)
    if not user:
        register_user(telegram_id, name)
        user = get_user(telegram_id)
        
        # process referral if code provided
        if context.args:
            referral_code = context.args[0]
            from app.payments import process_referral
            process_referral(telegram_id, referral_code)

    if not user or not user.get("terms_accepted"):
        keyboard = [[
            InlineKeyboardButton("✅ I Accept", callback_data="accept_terms"),
            InlineKeyboardButton("❌ I Decline", callback_data="decline_terms")
        ]]
        await update.message.reply_text(
            TERMS_TEXT,
            reply_markup=InlineKeyboardMarkup(keyboard)
        )
        return

    await send_welcome(update, name)

async def check_terms(update: Update) -> bool:
    telegram_id = update.effective_user.id
    user = get_user(telegram_id)
    if not user or not user.get("terms_accepted"):
        await update.message.reply_text(
            "Please send /start first and accept our terms to use StockOracle."
        )
        return False
    return True

async def send_welcome(update, name):
    await update.message.reply_text(
        f"👋 Welcome to StockOracle, {name}!\n\n"
        "I'm your AI-powered Nigerian stock market analyst. "
        "I scan 450+ NGX stocks daily and find the best opportunities for you.\n\n"
        "What I can do:\n"
        "- Weekly top 5 NGX stock signals with entry, take profit and stop loss\n"
        "- Real-time stock prices and analysis\n"
        "- AI conversation about any stock or market question\n"
        "- Chart and screenshot analysis\n"
        "- Take profit alerts when your stocks hit targets\n\n"
        "Commands:\n"
        "/signals — this week's top picks\n"
        "/explain GTCO — analyse any stock\n"
        "/subscribe — unlock full access\n"
        "/mystatus — check your subscription\n"
        "/performance — our track record\n"
        "/help — all commands\n\n"
        "Try asking me anything about Nigerian stocks — I'm here to help you invest properly."
    )

async def terms_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()
    telegram_id = query.from_user.id
    name = query.from_user.first_name or "there"

    if query.data == "accept_terms":
        supabase.table("users").update({
            "terms_accepted": True,
            "terms_accepted_at": datetime.now(UTC).isoformat()
        }).eq("telegram_id", telegram_id).execute()

        await query.edit_message_text("Terms accepted. Welcome to StockOracle!")
        await context.bot.send_message(
            chat_id=telegram_id,
            text=f"👋 Welcome to StockOracle, {name}!\n\n"
            "I scan 450+ NGX stocks daily to find the best opportunities.\n\n"
            "/signals — this week's top picks\n"
            "/explain GTCO — analyse any stock\n"
            "/subscribe — unlock full access\n"
            "/mystatus — check your subscription\n"
            "/help — all commands\n\n"
            "Ask me anything about Nigerian stocks!"
        )

    elif query.data == "decline_terms":
        await query.edit_message_text(
            "You declined the terms. StockOracle cannot be used without accepting them.\n\n"
            "Send /start if you change your mind."
        )
        # leave the bot — user declined

async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "StockOracle Commands:\n\n"
        "/signals — weekly stock picks with entry, TP and stop loss\n"
        "/explain GTCO — deep analysis of any NGX stock\n"
        "/performance — signal track record (wins and losses)\n"
        "/subscribe — view plans and subscribe\n"
        "/mystatus — check your subscription tier and expiry\n"
        "/clear — reset AI conversation\n\n"
        "Or just chat naturally — ask me anything about Nigerian stocks!"
    )

async def signals(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await check_terms(update):
        return
    telegram_id = update.effective_user.id
    user = get_user(telegram_id)

    result = supabase.table("signals")\
        .select("*")\
        .eq("status", "active")\
        .order("created_at", desc=True)\
        .limit(5)\
        .execute()

    if not result.data:
        await update.message.reply_text("No active signals yet. Check back Monday!")
        return

    if not is_paid(user):
        signal = result.data[0]
        msg = (
            "📊 This Week's NGX Signals\n\n"
            f"1. {signal['ticker']}\n"
            f"Entry: ₦{signal['entry_price']}\n"
            f"TP1: ₦{signal['tp1']} (+6%)\n"
            f"TP2: ₦{signal['tp2']} (+12%)\n"
            f"Stop Loss: ₦{signal['stop_loss']}\n\n"
            "Signals 2-5 are locked for subscribers.\n"
            "Use /subscribe to unlock all signals and take profit alerts."
        )
        await update.message.reply_text(msg)
        return

    msg = "📊 This Week's Top 5 NGX Signals\n\n"
    for i, s in enumerate(result.data, 1):
        msg += (
            f"{i}. {s['ticker']}\n"
            f"Entry: ₦{s['entry_price']}\n"
            f"TP1: ₦{s['tp1']} (+6%)\n"
            f"TP2: ₦{s['tp2']} (+12%)\n"
            f"Stop Loss: ₦{s['stop_loss']}\n\n"
        )
    msg += "⚠️ Always manage your risk. Never invest more than you can afford to lose."
    await update.message.reply_text(msg)

async def explain(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await check_terms(update):
        return
    telegram_id = update.effective_user.id
    user = get_user(telegram_id)
    args = context.args

    if not args:
        await update.message.reply_text("Usage: /explain GTCO")
        return

    if not is_paid(user):
        today_key = f"explain_{telegram_id}_{datetime.now(UTC).date()}"
        count = context.bot_data.get(today_key, 0)
        if count >= 2:
            await update.message.reply_text(
                "You've used your 2 free lookups today.\n"
                "Subscribe for unlimited lookups.\n\n"
                "Use /subscribe to upgrade."
            )
            return
        context.bot_data[today_key] = count + 1

    ticker = args[0].upper()
    result = supabase.table("stocks")\
        .select("*")\
        .eq("ticker", ticker)\
        .order("scraped_at", desc=True)\
        .limit(1)\
        .execute()

    if not result.data:
        await update.message.reply_text(f"Ticker {ticker} not found.")
        return

    stock = result.data[0]
    await update.message.reply_text(
        f"📊 {stock['ticker']} — {stock['company']}\n\n"
        f"Price: {stock['price']}\n"
        f"Change: {stock['change']}\n"
        f"Signal: {stock['signal']}\n"
        f"Volume: {stock['volume']}\n\n"
        "Ask me anything about this stock for deeper analysis."
    )

async def subscribe(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await check_terms(update):
        return
    
    keyboard = [
        [InlineKeyboardButton("Basic — ₦5,999/month", callback_data="subscribe_basic")],
        [InlineKeyboardButton("Pro — ₦9,999/month", callback_data="subscribe_pro")],
        [InlineKeyboardButton("❌ Cancel", callback_data="subscribe_cancel")],
    ]
    await update.message.reply_text(
        "StockOracle Plans:\n\n"
        "Basic — ₦5,999/month\n"
        "- All 5 weekly signals in real time every Monday\n"
        "- Take profit and stop loss alerts\n"
        "- Unlimited stock lookups\n"
        "- Full AI market analysis\n\n"
        "Pro — ₦9,999/month\n"
        "- Everything in Basic\n"
        "- Daily signals Tuesday to Friday\n"
        "- Portfolio audit with PDF report\n"
        "- Priority AI responses\n"
        "- Full performance track record\n\n"
        "Choose your plan:",
        reply_markup=InlineKeyboardMarkup(keyboard)
    )

async def subscribe_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()

    if query.data == "subscribe_cancel" or query.data == "pay_cancel":
        context.user_data.pop("pending_plan", None)
        context.user_data.pop("pending_provider", None)
        await query.edit_message_text("Subscription cancelled. Send /subscribe anytime to upgrade.")
        return

    if query.data.startswith("subscribe_"):
        plan = "basic" if query.data == "subscribe_basic" else "pro"
        context.user_data["pending_plan"] = plan

        keyboard = [
            [InlineKeyboardButton("Pay with Paystack", callback_data=f"pay_paystack_{plan}")],
            [InlineKeyboardButton("Pay with Flutterwave", callback_data=f"pay_flutterwave_{plan}")],
            [InlineKeyboardButton("Pay with Korapay", callback_data=f"pay_korapay_{plan}")],
            [InlineKeyboardButton("❌ Cancel", callback_data="pay_cancel")],
        ]
        tier = "Basic" if plan == "basic" else "Pro"
        await query.edit_message_text(
            f"You selected {tier} (₦{'5,999' if plan == 'basic' else '9,999'}/month)\n\n"
            "Choose your payment method:",
            reply_markup=InlineKeyboardMarkup(keyboard)
        )

    elif query.data.startswith("pay_"):
        parts = query.data.split("_")
        provider = parts[1]
        plan = parts[2]
        context.user_data["pending_plan"] = plan
        context.user_data["pending_provider"] = provider
        await query.edit_message_text(
            f"Please reply with your email address to continue with {provider.capitalize()}:\n\n"
            "Or send /cancel to stop."
        )

async def my_status(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await check_terms(update):
        return
    telegram_id = update.effective_user.id
    name = update.effective_user.first_name or "there"

    user = get_user(telegram_id)
    if not user:
        register_user(telegram_id, name)
        user = get_user(telegram_id)

    tier = user.get("tier", "free").capitalize()

    if is_paid(user):
        expires = user.get("expires_at", "")[:10]
        await update.message.reply_text(
            f"Your subscription: {tier}\n"
            f"Active until: {expires}\n\n"
            "Enjoying StockOracle? Tell a friend!"
        )
    else:
        await update.message.reply_text(
            f"Your plan: Free\n\n"
            "You're on the free tier. Upgrade to unlock:\n"
            "- All 5 weekly signals every Monday\n"
            "- Take profit and stop loss alerts\n"
            "- Unlimited AI stock analysis\n"
            "- Portfolio audit\n\n"
            "Use /subscribe to upgrade."
        )

async def cancel(update: Update, context: ContextTypes.DEFAULT_TYPE):
    context.user_data.pop("pending_plan", None)
    context.user_data.pop("pending_provider", None)
    await update.message.reply_text("Cancelled. Send /subscribe anytime to upgrade.")


async def audit(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await check_terms(update):
        return
    telegram_id = update.effective_user.id
    user_name = update.effective_user.first_name or "User"
    user = get_user(telegram_id)

    if not is_pro(user):
        await update.message.reply_text(
            "Portfolio audit is a Pro feature.\n\n"
            "Upgrade to Pro (₦9,999/month) to get:\n"
            "- Full portfolio audit with sector breakdown\n"
            "- Concentration risk scoring\n"
            "- PDF report you can save and share\n\n"
            "Use /subscribe to upgrade."
        )
        return

    args = context.args
    if not args:
        await update.message.reply_text(
            "Paste your holdings after /audit like this:\n\n"
            "/audit 5000 GTCO at 48, 2000 MTNN at 218, 10000 WEMABANK at 34\n\n"
            "Format: quantity TICKER at buy_price"
        )
        return

    holdings_text = " ".join(args)
    thinking_msg = await update.message.reply_text("📊 Generating your portfolio audit...")

    try:
        from app.pdf_generator import generate_portfolio_pdf
        import io

        pdf_bytes = generate_portfolio_pdf(holdings_text, user_name)

        if not pdf_bytes:
            await thinking_msg.edit_text(
                "Could not parse your holdings. Please use this format:\n"
                "/audit 5000 GTCO at 48, 2000 MTNN at 218"
            )
            return

        await thinking_msg.delete()
        await update.message.reply_document(
            document=io.BytesIO(pdf_bytes),
            filename=f"StockOracle_Portfolio_Audit_{datetime.now().strftime('%Y%m%d')}.pdf",
            caption="Your portfolio audit is ready. Review the risk assessment and sector breakdown carefully."
        )
    except Exception as e:
        logger.error(f"Audit error: {e}")
        await thinking_msg.edit_text("Something went wrong generating your audit. Please try again.")


async def performance(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await check_terms(update):
        return
    result = supabase.table("signal_history")\
        .select("*")\
        .neq("outcome", "pending")\
        .order("closed_at", desc=True)\
        .limit(20)\
        .execute()

    if not result.data:
        await update.message.reply_text(
            "Track record is building. Check back after our first signals close.\n\n"
            "Every signal outcome is recorded automatically — wins and losses both."
        )
        return

    records = result.data
    wins = [r for r in records if r["outcome"] == "tp1_hit"]
    losses = [r for r in records if r["outcome"] == "stopped_out"]
    win_rate = round(len(wins) / len(records) * 100) if records else 0
    avg_gain = round(sum(r["gain_percentage"] for r in records if r["gain_percentage"]) / len(records), 2) if records else 0

    msg = (
        f"📈 StockOracle Track Record\n\n"
        f"Total signals closed: {len(records)}\n"
        f"Win rate: {win_rate}%\n"
        f"Average return: {avg_gain}%\n"
        f"Wins: {len(wins)} | Losses: {len(losses)}\n\n"
        "Recent signals:\n"
    )
    for r in records[:5]:
        emoji = "✅" if r["outcome"] == "tp1_hit" else "❌"
        msg += f"{emoji} {r['ticker']} — {r['gain_percentage']}%\n"

    await update.message.reply_text(msg)

async def clear(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    if user_id in user_histories:
        del user_histories[user_id]
    await update.message.reply_text("Conversation cleared. Fresh start!")

async def handle_email_for_subscription(update: Update, context: ContextTypes.DEFAULT_TYPE) -> bool:
    telegram_id = update.effective_user.id
    pending_plan = context.user_data.get("pending_plan")
    pending_provider = context.user_data.get("pending_provider", "paystack")

    if not pending_plan:
        return False

    email = update.message.text.strip()
    if "@" not in email or "." not in email:
        await update.message.reply_text("That doesn't look like a valid email. Please try again.")
        return True

    link = None
    if pending_provider == "paystack":
        plan_code = PAYSTACK_BASIC_PLAN if pending_plan == "basic" else PAYSTACK_PRO_PLAN
        link = create_subscription_link(email, plan_code, telegram_id)
    elif pending_provider == "flutterwave":
        from app.payments import create_flutterwave_link
        link = create_flutterwave_link(email, pending_plan, telegram_id)
    elif pending_provider == "korapay":
        from app.payments import create_korapay_link
        link = create_korapay_link(email, pending_plan, telegram_id)

    context.user_data.pop("pending_plan", None)
    context.user_data.pop("pending_provider", None)

    if not link:
        await update.message.reply_text("Something went wrong. Please try /subscribe again.")
        return True

    tier_name = "Basic" if pending_plan == "basic" else "Pro"
    amount = "₦5,999" if pending_plan == "basic" else "₦9,999"

    await update.message.reply_text(
        f"Your {tier_name} payment link is ready.\n\n"
        f"Amount: {amount}/month\n\n"
        f"Pay here:\n{link}\n\n"
        "Your account upgrades automatically once payment is confirmed."
    )
    return True

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    user_name = update.effective_user.first_name or "there"
    user_message = update.message.text or ""
    image_data = None
    image_mime = None

    if not await check_terms(update):
        return

    if context.user_data.get("pending_plan"):
        handled = await handle_email_for_subscription(update, context)
        if handled:
            return

    if update.message.photo:
        photo = update.message.photo[-1]
        file = await context.bot.get_file(photo.file_id)
        image_data = await file.download_as_bytearray()
        image_mime = "image/jpeg"
        user_message = update.message.caption or ""

    user = get_user(user_id)

    if user_id not in user_histories:
        user_histories[user_id] = []

    thinking_msg = await update.message.reply_text("🤔 Analysing...")

    response, updated_history = get_ai_response(
        user_message, user_name, image_data, image_mime, user_histories[user_id]
    )

    user_histories[user_id] = updated_history[-20:]

    await thinking_msg.delete()
    await update.message.reply_text(response)
    

async def watchlist_add(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await check_terms(update):
        return
    
    telegram_id = update.effective_user.id
    args = context.args
    
    if not args:
        await update.message.reply_text("Usage: /watch GTCO")
        return
    
    ticker = args[0].upper()
    
    # verify ticker exists
    result = supabase.table("stocks")\
        .select("ticker, company")\
        .eq("ticker", ticker)\
        .limit(1)\
        .execute()
    
    if not result.data:
        await update.message.reply_text(f"{ticker} not found. Check the ticker and try again.")
        return
    
    try:
        supabase.table("watchlist").insert({
            "telegram_id": telegram_id,
            "ticker": ticker
        }).execute()
        company = result.data[0]["company"]
        await update.message.reply_text(
            f"{ticker} ({company}) added to your watchlist.\n\n"
            "You'll get daily price updates on this stock.\n"
            "Use /watchlist to see all your stocks."
        )
    except Exception as e:
        if "unique" in str(e).lower():
            await update.message.reply_text(f"{ticker} is already in your watchlist.")
        else:
            await update.message.reply_text("Something went wrong. Please try again.")

async def watchlist_view(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await check_terms(update):
        return
    
    telegram_id = update.effective_user.id
    
    result = supabase.table("watchlist")\
        .select("ticker")\
        .eq("telegram_id", telegram_id)\
        .execute()
    
    if not result.data:
        await update.message.reply_text(
            "Your watchlist is empty.\n\n"
            "Add stocks with /watch GTCO"
        )
        return
    
    tickers = [r["ticker"] for r in result.data]
    msg = "Your Watchlist:\n\n"
    
    for ticker in tickers:
        stock = supabase.table("stocks")\
            .select("price, change, signal")\
            .eq("ticker", ticker)\
            .order("scraped_at", desc=True)\
            .limit(1)\
            .execute()
        
        if stock.data:
            s = stock.data[0]
            msg += f"{ticker} — {s['price']} | {s['change']} | {s['signal']}\n"
        else:
            msg += f"{ticker} — no data\n"
    
    msg += "\nRemove a stock: /unwatch GTCO"
    await update.message.reply_text(msg)

async def referral(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await check_terms(update):
        return
    
    telegram_id = update.effective_user.id
    from app.payments import get_or_create_referral_code
    
    code = get_or_create_referral_code(telegram_id)
    bot_username = (await context.bot.get_me()).username
    
    await update.message.reply_text(
        f"Your referral code: {code}\n\n"
        f"Share this link with friends:\n"
        f"https://t.me/{bot_username}?start={code}\n\n"
        "When a friend joins using your link and subscribes, "
        "you automatically get 7 free days added to your subscription.\n\n"
        "There's no limit — refer 4 friends and get a free month!"
    )


async def watchlist_remove(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not await check_terms(update):
        return
    
    telegram_id = update.effective_user.id
    args = context.args
    
    if not args:
        await update.message.reply_text("Usage: /unwatch GTCO")
        return
    
    ticker = args[0].upper()
    
    supabase.table("watchlist")\
        .delete()\
        .eq("telegram_id", telegram_id)\
        .eq("ticker", ticker)\
        .execute()
    
    await update.message.reply_text(f"{ticker} removed from your watchlist.")

def run_bot():
    return Application.builder().token(TELEGRAM_BOT_TOKEN).build()